CREATE TABLE IF NOT EXISTS reference_data (
  id SERIAL PRIMARY KEY,
  feature1 DOUBLE PRECISION,
  feature2 DOUBLE PRECISION,
  feature3 DOUBLE PRECISION,
  target INTEGER
);

CREATE TABLE IF NOT EXISTS new_data (
  id SERIAL PRIMARY KEY,
  feature1 DOUBLE PRECISION,
  feature2 DOUBLE PRECISION,
  feature3 DOUBLE PRECISION,
  target INTEGER
);